// <auto-generated />
namespace AcademicManagement.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAcademicPeriodTablle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAcademicPeriodTablle));
        
        string IMigrationMetadata.Id
        {
            get { return "201902192042141_AddAcademicPeriodTablle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
